<?php
const ALL_PICTURES = 80;
const FELT_TIP_PEN_DRAWINGS = 23;
const PENCIL_DRAWINGS = 40;
const DRAWINGS_WITH_PAINTS = ALL_PICTURES - FELT_TIP_PEN_DRAWINGS - PENCIL_DRAWINGS;
echo (DRAWINGS_WITH_PAINTS);
?>